### ISSUE TITLE
configure: script should be executable

### ISSUE THREAD

**Issue by bmarwell** [ibmruntimes/openj9-openjdk-jdk17#137]
It is uncommon to call it using `bash configure`. Instead, use POSIX defaults so it will also build on all POSIX compliant OSes: `./configure`.

PR is ready.

**Comment by keithc-ca** [comment]
While I understand that it's common for projects to have an executable `configure` script, the [build instructions](https://github.com/ibmruntimes/openj9-openjdk-jdk17/blob/openj9/doc/building.md) clearly state that one should say `bash configure ...`; that advice is repeated in [OpenJ9](https://github.com/eclipse-openj9/openj9/blob/master/doc/build-instructions/Build_Instructions_V17.md). If you feel strongly about this, it is an issue you should take up with the upstream projects from openjdk.
