### ISSUE TITLE
missing `openj9-0.39.0` tag?

### ISSUE THREAD

**Issue by chenrui333** [ibmruntimes/openj9-openjdk-jdk17#222]
While trying to upgrade [openj9 to the latest release](https://github.com/Homebrew/homebrew-core/pull/133759), I found there is missing tag with `openj9-0.39.0` in the repo. Create this issue to confirm if that is intentional, thanks!

**Comment by pshipton** [comment]
The 0.39 release only support jdk20.

**Comment by pshipton** [comment]
And it's true there is no openj9-0.39.0 tag on the jdk20 repo, I will create it after the Semeru builds are successfully created.

**Comment by chenrui333** [comment]
> And it's true there isn't yet an openj9-0.39.0 tag on the jdk20 repo, I will create it after the Semeru builds are successfully created. The head of the v0.39.0-release branch can be used in the meantime.

got you, thanks!!

**Comment by chenrui333** [comment]
I think I am all set now, thanks!
