### ISSUE TITLE
Broken Eclipse link in readme

### ISSUE THREAD

**Issue by gjwatts** [ibmruntimes/openj9-openjdk-jdk17#27]
The link on the main repos for openj9-openjdk-jdkXX pages [How to build Eclipse OpenJ9](https://github.com/ibmruntimes/openj9-openjdk-jdk17) in the Readme sections point [here](https://www.eclipse.org/openj9/oj9_build.html) and that gives back an error 404 from within the Eclipse site.

**Comment by keithc-ca** [comment]
I also noticed https://github.com/eclipse-openj9/openj9-docs/issues/846, which is fixed by https://github.com/eclipse-openj9/openj9-docs/issues/847.

**Comment by keithc-ca** [comment]
Fixed via PRs referenced above.
