### ISSUE TITLE
Invalid ConstantPool when instrumenting a class with -Xshare:off VM option

### ISSUE THREAD

**Issue by erichhochmuth** [ibmruntimes/openj9-openjdk-jdk17#85]
When instrumenting a class (in our case javax.management.ObjectName) and add a MethodHandle to the ConstantPool in the ClassFileLoadHook, it appears that the original ConstantPool is used while the Attributes are used from the instrumented class.

Tested with 17.0.2.0 (build 17.0.2+8) and current 
> openjdk version "17.0.3-internal" 2022-04-19
> OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..hostdir)
> Eclipse OpenJ9 VM (build master-eb8be6913, JRE 17 Linux amd64-64-Bit Compressed References 20220411_000000 (JIT enabled, AOT enabled)
> OpenJ9   - eb8be6913
> OMR      - 48d41b458
> JCL      - aff77b6333b based on jdk-17.0.3+5)

Result is a crash with a assertion error:

> 21:00:26.027 0x21f00j9bcu(j9vm).129    *   ** ASSERTION FAILED ** at /root/hostdir/openj9/runtime/bcutil/ClassFileOracle.cpp:2720: ((15 == _classFile->constantPool[cpIndex].tag))

Stacktrace from gdb
[stacktrace.txt](https://github.com/ibmruntimes/openj9-openjdk-jdk17/files/8468093/stacktrace.txt)

The classfile has the original constantPoolCount:
`(gdb) print *_classFile
$56 = {magic = 3405691582, minorVersion = 0, majorVersion = 61, accessFlags = 33, j9Flags = 0, thisClass = 1, superClass = 381, 
  constantPoolCount = 749, interfacesCount = 2, fieldsCount = 19, methodsCount = 50, attributesCount = 5, firstUTF8CPIndex = 2, 
  lastUTF8CPIndex = 748, firstNATCPIndex = 8, constantPool = 0x7ffff14a81e0, interfaces = 0x7ffff14aff56, fields = 0x7ffff14aff60, 
  methods = 0x7ffff14b02c0, attributes = 0x7ffff14b7328, classFileSize = 24511}
`

While the BoostrapMethods attribute points to the ConstantPool index of the added MethodHandle:
`(gdb) print *_bootstrapMethodsAttribute->bootstrapMethods
$57 = {bootstrapMethodIndex = 773, numberOfBootstrapArguments = 1, bootstrapArguments = 0x7ffff14b74b8}
`

Iff necessary, we can create a reproducer. Same code works when -Xshare:off is not set and on openjdk with -Xshare:off set.

**Comment by pshipton** [comment]
@erichhochmuth pls open this at https://github.com/eclipse-openj9/openj9/issues rather than here.

**Comment by erichhochmuth** [comment]
Thanks, will do.
